### ISSUE TITLE
Make cd .. work

### ISSUE THREAD

**Issue by muhammadmuzzammil1998** [SecureWindowsShell/SWSH#2]
```cd ..``` is not working...

**Comment by omern1** [comment]
Based on our conversation earlier I thought we had decided to just pass the users commands to the server?

**Comment by muhammadmuzzammil1998** [comment]
Yes we did... But this needs to be fixed... (It's personal 🤣 )

**Comment by muhammadmuzzammil1998** [comment]
Fixed in beta-1.0 
e87f38b7bac7d4a444b0ebc3041599f1e7c6e670
