### ISSUE TITLE
Username is not added to connection file when equal to nickname

### ISSUE THREAD

**Issue by drieseng** [SecureWindowsShell/SWSH#23]
Version of SWSH: beta-1.4.1

When the nickname that you enter for a given connection is equal to the username, then the username is not added to the connection file that is created.

This is due to the `Except` here:
https://github.com/muhammadmuzzammil1998/SWSH/blob/51d06c6dec5f367abec86aa1e3332129ee000a99/SWSH/Program.cs#L154
If I'm not mistaken this also leads to an exception when you attempt to use the connection.

**Comment by muhammadmuzzammil1998** [comment]
Thank you, I'll look into it...

**Comment by muhammadmuzzammil1998** [comment]
It is fixed, thank you for your contribution. :)
